/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_angelrisso;

import javax.swing.JOptionPane;

/**
 *
 * @author HP_AMD_64
 */
public class Multiverso extends javax.swing.JFrame {

    /**
     * Creates new form Multiverso
     */
    public Multiverso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_cUni = new javax.swing.JDialog();
        bt_seres = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tf_raza = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sp_edad = new javax.swing.JSpinner();
        sp_ki = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        tf_planeta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jd_eliiminar = new javax.swing.JDialog();
        bt_universo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jd_cUni.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jd_cUni.setMinimumSize(new java.awt.Dimension(618, 492));
        jd_cUni.setModal(true);
        jd_cUni.getContentPane().setLayout(null);

        bt_seres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_seres.setText("Crear Seres");
        bt_seres.setOpaque(false);
        bt_seres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seresActionPerformed(evt);
            }
        });
        jd_cUni.getContentPane().add(bt_seres);
        bt_seres.setBounds(290, 360, 120, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Raza del ser");
        jd_cUni.getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 110, 22);

        tf_raza.setText(" ");
        jd_cUni.getContentPane().add(tf_raza);
        tf_raza.setBounds(140, 110, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edad");
        jd_cUni.getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 150, 50, 22);

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jd_cUni.getContentPane().add(sp_edad);
        sp_edad.setBounds(140, 150, 60, 30);
        jd_cUni.getContentPane().add(sp_ki);
        sp_ki.setBounds(140, 200, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ki");
        jd_cUni.getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 200, 20, 22);

        tf_planeta.setText(" ");
        jd_cUni.getContentPane().add(tf_planeta);
        tf_planeta.setBounds(140, 260, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("planeta ");
        jd_cUni.getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 260, 80, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6_angelrisso/epic space face.jpg"))); // NOI18N
        jd_cUni.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 470);

        javax.swing.GroupLayout jd_eliiminarLayout = new javax.swing.GroupLayout(jd_eliiminar.getContentPane());
        jd_eliiminar.getContentPane().setLayout(jd_eliiminarLayout);
        jd_eliiminarLayout.setHorizontalGroup(
            jd_eliiminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_eliiminarLayout.setVerticalGroup(
            jd_eliiminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bt_universo.setText("CREAR UNIVERSO Y AÑADIR SERES");
        bt_universo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_universoMouseClicked(evt);
            }
        });
        getContentPane().add(bt_universo);
        bt_universo.setBounds(40, 30, 210, 120);

        jButton2.setText("eliminar seres");
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 320, 200, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6_angelrisso/fourstar.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 760, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_universoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_universoMouseClicked
        if (ban < 1) {
            ban++;
            String nombre = JOptionPane.showInputDialog("Ingrese el nombre de este universo");

            u.setNombre(nombre);
        } else {
            JOptionPane.showMessageDialog(this, "ya existe un universo");
        }

        jd_cUni.pack();
        jd_cUni.setModal(true);
        jd_cUni.setVisible(true);
        jd_cUni.setLocationRelativeTo(this);
    }//GEN-LAST:event_bt_universoMouseClicked

    private void bt_seresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seresActionPerformed
        if (tf_raza.getText().equals(" ") || tf_raza.getText().equals(" ")) {
            JOptionPane.showMessageDialog(this, "No puede tener espacios sin nada");
            
        } else {

            String raza = "";
            int años = 0;
            int ki = 0;
            String planeta = "";

            raza = tf_raza.getText();
            años = (Integer) sp_edad.getValue();
            ki = (Integer) sp_ki.getValue();
            JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            u.setHabitantes(new Ser_vivo(raza, ki, años, planeta));

            tf_raza.setText(" ");
            sp_edad.setValue(0);
            sp_ki.setValue(0);
            tf_planeta.setText(" ");
        }

        System.out.println(u.getHabitantes());
    }//GEN-LAST:event_bt_seresActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Multiverso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Multiverso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Multiverso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Multiverso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Multiverso().setVisible(true);
            }
        });
    }
    Universo uni;
    Universo u = new Universo();
    int ban = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_seres;
    private javax.swing.JButton bt_universo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JDialog jd_cUni;
    private javax.swing.JDialog jd_eliiminar;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_ki;
    private javax.swing.JTextField tf_planeta;
    private javax.swing.JTextField tf_raza;
    // End of variables declaration//GEN-END:variables
}
